#!/bin/bash

#get cmd line arguments
  while [[ "$#" -gt 0 ]]; do case $1 in
    -u|--user) accountname="$2"; shift;;
    *) echo "Unknown parameter passed: $1"; exit 1;;
  esac; shift; done

#remove service account and binding
if [ -z "$accountname" ]; then
  echo "Account Name Not Specified"
else
  exist=$(kubectl get serviceaccount -n kube-system --no-headers "$accountname" | cut -f1 -d ' ')
  if [ "$exist" = "$accountname" ]; then
    read -p "$accountname Found - Delete? y/n: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      kubectl delete clusterrolebinding "$accountname-crb"
      kubectl delete serviceaccount "$accountname" --namespace kube-system
    fi
  else
    echo "Account Not Found"
  fi
fi
