#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ -e ~/inventory/hosts-master ]]; then
  file=~/inventory/hosts-master
else
  file=~/inventory/hosts-controller
fi

endpoints=$(< $file awk '$0="https://"$0":2379"' | paste -sd "," -)

/media/root/usr/bin/etcdctl --endpoints="$endpoints" $@
