#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

user=$(grep -m 1 -oPe '[.\w]+(?=-sfmc-docker)' /etc/mtab)

if [[ -e ~/inventory/hosts-master ]]; then
  file=~/inventory/hosts-master
else
  file=~/inventory/hosts-controller
fi

slex --hosts $file --user $user --agent $@
